# Generated by Django 4.0.5 on 2022-06-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(default='DEFAULT VALUE', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
